/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SignRouteImport } from './routes/sign'
import { Route as UnreachableRouteImport } from './routes/unreachable'
import { Route as AuthedAppRouteImport } from './routes/_authed/_app'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as AuthedSettingsRouteRouteImport } from './routes/_authed/settings/route'
import { Route as AuthedWelcomeRouteImport } from './routes/_authed/welcome'
import { Route as AuthedAppIndexRouteImport } from './routes/_authed/_app/index'
import { Route as AuthedAppRoutinesRouteImport } from './routes/_authed/_app/routines'
import { Route as AuthedAppSkillsRouteImport } from './routes/_authed/_app/skills'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedAdminAuditRouteImport } from './routes/_authed/admin/audit'
import { Route as AuthedAdminBoundariesRouteImport } from './routes/_authed/admin/boundaries'
import { Route as AuthedAdminComponentsRouteImport } from './routes/_authed/admin/components'
import { Route as AuthedAdminComputersRouteImport } from './routes/_authed/admin/computers'
import { Route as AuthedAdminCredentialsRouteImport } from './routes/_authed/admin/credentials'
import { Route as AuthedAdminPlaygroundRouteImport } from './routes/_authed/admin/playground'
import { Route as AuthedAdminPluginsRouteImport } from './routes/_authed/admin/plugins'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedSettingsAccountRouteImport } from './routes/_authed/settings/account'
import { Route as AuthedSettingsConnectedAccountsRouteImport } from './routes/_authed/settings/connected-accounts'
import { Route as AuthedAppAgentsIndexRouteImport } from './routes/_authed/_app/agents/index'
import { Route as AuthedAppApproveApprovalIdRouteImport } from './routes/_authed/_app/approve/$approvalId'
import { Route as AuthedAppChannelChannelIdRouteImport } from './routes/_authed/_app/channel/$channelId'
import { Route as AuthedAppChannelNewRouteImport } from './routes/_authed/_app/channel/new'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const UnreachableRoute = UnreachableRouteImport.update({
  id: '/unreachable',
  path: '/unreachable',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRouteRoute = AuthedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWelcomeRoute = AuthedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppIndexRoute = AuthedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppRoutinesRoute = AuthedAppRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppSkillsRoute = AuthedAppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminAuditRoute = AuthedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminBoundariesRoute = AuthedAdminBoundariesRouteImport.update({
  id: '/boundaries',
  path: '/boundaries',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminComponentsRoute = AuthedAdminComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminComputersRoute = AuthedAdminComputersRouteImport.update({
  id: '/computers',
  path: '/computers',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminCredentialsRoute = AuthedAdminCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminPlaygroundRoute = AuthedAdminPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminPluginsRoute = AuthedAdminPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRouteRoute,
} as any)
const AuthedSettingsAccountRoute = AuthedSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedSettingsRouteRoute,
} as any)
const AuthedSettingsConnectedAccountsRoute =
  AuthedSettingsConnectedAccountsRouteImport.update({
    id: '/connected-accounts',
    path: '/connected-accounts',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedAppAgentsIndexRoute = AuthedAppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppApproveApprovalIdRoute =
  AuthedAppApproveApprovalIdRouteImport.update({
    id: '/approve/$approvalId',
    path: '/approve/$approvalId',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppChannelChannelIdRoute =
  AuthedAppChannelChannelIdRouteImport.update({
    id: '/channel/$channelId',
    path: '/channel/$channelId',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppChannelNewRoute = AuthedAppChannelNewRouteImport.update({
  id: '/channel/new',
  path: '/channel/new',
  getParentRoute: () => AuthedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedAppIndexRoute
  '/sign': typeof SignRoute
  '/unreachable': typeof UnreachableRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/welcome': typeof AuthedWelcomeRoute
  '/routines': typeof AuthedAppRoutinesRoute
  '/skills': typeof AuthedAppSkillsRoute
  '/admin/audit': typeof AuthedAdminAuditRoute
  '/admin/boundaries': typeof AuthedAdminBoundariesRoute
  '/admin/components': typeof AuthedAdminComponentsRoute
  '/admin/computers': typeof AuthedAdminComputersRoute
  '/admin/credentials': typeof AuthedAdminCredentialsRoute
  '/admin/playground': typeof AuthedAdminPlaygroundRoute
  '/admin/plugins': typeof AuthedAdminPluginsRoute
  '/settings/account': typeof AuthedSettingsAccountRoute
  '/settings/connected-accounts': typeof AuthedSettingsConnectedAccountsRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/approve/$approvalId': typeof AuthedAppApproveApprovalIdRoute
  '/channel/$channelId': typeof AuthedAppChannelChannelIdRoute
  '/channel/new': typeof AuthedAppChannelNewRoute
  '/agents/': typeof AuthedAppAgentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedAppIndexRoute
  '/sign': typeof SignRoute
  '/unreachable': typeof UnreachableRoute
  '/welcome': typeof AuthedWelcomeRoute
  '/routines': typeof AuthedAppRoutinesRoute
  '/skills': typeof AuthedAppSkillsRoute
  '/admin/audit': typeof AuthedAdminAuditRoute
  '/admin/boundaries': typeof AuthedAdminBoundariesRoute
  '/admin/components': typeof AuthedAdminComponentsRoute
  '/admin/computers': typeof AuthedAdminComputersRoute
  '/admin/credentials': typeof AuthedAdminCredentialsRoute
  '/admin/playground': typeof AuthedAdminPlaygroundRoute
  '/admin/plugins': typeof AuthedAdminPluginsRoute
  '/settings/account': typeof AuthedSettingsAccountRoute
  '/settings/connected-accounts': typeof AuthedSettingsConnectedAccountsRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/approve/$approvalId': typeof AuthedAppApproveApprovalIdRoute
  '/channel/$channelId': typeof AuthedAppChannelChannelIdRoute
  '/channel/new': typeof AuthedAppChannelNewRoute
  '/agents': typeof AuthedAppAgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign': typeof SignRoute
  '/unreachable': typeof UnreachableRoute
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/_authed/_app': typeof AuthedAppRouteWithChildren
  '/_authed/welcome': typeof AuthedWelcomeRoute
  '/_authed/_app/routines': typeof AuthedAppRoutinesRoute
  '/_authed/_app/skills': typeof AuthedAppSkillsRoute
  '/_authed/admin/audit': typeof AuthedAdminAuditRoute
  '/_authed/admin/boundaries': typeof AuthedAdminBoundariesRoute
  '/_authed/admin/components': typeof AuthedAdminComponentsRoute
  '/_authed/admin/computers': typeof AuthedAdminComputersRoute
  '/_authed/admin/credentials': typeof AuthedAdminCredentialsRoute
  '/_authed/admin/playground': typeof AuthedAdminPlaygroundRoute
  '/_authed/admin/plugins': typeof AuthedAdminPluginsRoute
  '/_authed/settings/account': typeof AuthedSettingsAccountRoute
  '/_authed/settings/connected-accounts': typeof AuthedSettingsConnectedAccountsRoute
  '/_authed/_app/': typeof AuthedAppIndexRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/_app/approve/$approvalId': typeof AuthedAppApproveApprovalIdRoute
  '/_authed/_app/channel/$channelId': typeof AuthedAppChannelChannelIdRoute
  '/_authed/_app/channel/new': typeof AuthedAppChannelNewRoute
  '/_authed/_app/agents/': typeof AuthedAppAgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign'
    | '/unreachable'
    | '/admin'
    | '/settings'
    | '/welcome'
    | '/routines'
    | '/skills'
    | '/admin/audit'
    | '/admin/boundaries'
    | '/admin/components'
    | '/admin/computers'
    | '/admin/credentials'
    | '/admin/playground'
    | '/admin/plugins'
    | '/settings/account'
    | '/settings/connected-accounts'
    | '/admin/'
    | '/settings/'
    | '/approve/$approvalId'
    | '/channel/$channelId'
    | '/channel/new'
    | '/agents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign'
    | '/unreachable'
    | '/welcome'
    | '/routines'
    | '/skills'
    | '/admin/audit'
    | '/admin/boundaries'
    | '/admin/components'
    | '/admin/computers'
    | '/admin/credentials'
    | '/admin/playground'
    | '/admin/plugins'
    | '/settings/account'
    | '/settings/connected-accounts'
    | '/admin'
    | '/settings'
    | '/approve/$approvalId'
    | '/channel/$channelId'
    | '/channel/new'
    | '/agents'
  id:
    | '__root__'
    | '/_authed'
    | '/sign'
    | '/unreachable'
    | '/_authed/admin'
    | '/_authed/settings'
    | '/_authed/_app'
    | '/_authed/welcome'
    | '/_authed/_app/routines'
    | '/_authed/_app/skills'
    | '/_authed/admin/audit'
    | '/_authed/admin/boundaries'
    | '/_authed/admin/components'
    | '/_authed/admin/computers'
    | '/_authed/admin/credentials'
    | '/_authed/admin/playground'
    | '/_authed/admin/plugins'
    | '/_authed/settings/account'
    | '/_authed/settings/connected-accounts'
    | '/_authed/_app/'
    | '/_authed/admin/'
    | '/_authed/settings/'
    | '/_authed/_app/approve/$approvalId'
    | '/_authed/_app/channel/$channelId'
    | '/_authed/_app/channel/new'
    | '/_authed/_app/agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignRoute: typeof SignRoute
  UnreachableRoute: typeof UnreachableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unreachable': {
      id: '/unreachable'
      path: '/unreachable'
      fullPath: '/unreachable'
      preLoaderRoute: typeof UnreachableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_app': {
      id: '/_authed/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/welcome': {
      id: '/_authed/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthedWelcomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_app/': {
      id: '/_authed/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/routines': {
      id: '/_authed/_app/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof AuthedAppRoutinesRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/skills': {
      id: '/_authed/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthedAppSkillsRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/audit': {
      id: '/_authed/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthedAdminAuditRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/boundaries': {
      id: '/_authed/admin/boundaries'
      path: '/boundaries'
      fullPath: '/admin/boundaries'
      preLoaderRoute: typeof AuthedAdminBoundariesRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/components': {
      id: '/_authed/admin/components'
      path: '/components'
      fullPath: '/admin/components'
      preLoaderRoute: typeof AuthedAdminComponentsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/computers': {
      id: '/_authed/admin/computers'
      path: '/computers'
      fullPath: '/admin/computers'
      preLoaderRoute: typeof AuthedAdminComputersRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/credentials': {
      id: '/_authed/admin/credentials'
      path: '/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AuthedAdminCredentialsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/playground': {
      id: '/_authed/admin/playground'
      path: '/playground'
      fullPath: '/admin/playground'
      preLoaderRoute: typeof AuthedAdminPlaygroundRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/plugins': {
      id: '/_authed/admin/plugins'
      path: '/plugins'
      fullPath: '/admin/plugins'
      preLoaderRoute: typeof AuthedAdminPluginsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/account': {
      id: '/_authed/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthedSettingsAccountRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/connected-accounts': {
      id: '/_authed/settings/connected-accounts'
      path: '/connected-accounts'
      fullPath: '/settings/connected-accounts'
      preLoaderRoute: typeof AuthedSettingsConnectedAccountsRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/_app/agents/': {
      id: '/_authed/_app/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthedAppAgentsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/approve/$approvalId': {
      id: '/_authed/_app/approve/$approvalId'
      path: '/approve/$approvalId'
      fullPath: '/approve/$approvalId'
      preLoaderRoute: typeof AuthedAppApproveApprovalIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/channel/$channelId': {
      id: '/_authed/_app/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof AuthedAppChannelChannelIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/channel/new': {
      id: '/_authed/_app/channel/new'
      path: '/channel/new'
      fullPath: '/channel/new'
      preLoaderRoute: typeof AuthedAppChannelNewRouteImport
      parentRoute: typeof AuthedAppRoute
    }
  }
}

interface AuthedAdminRouteRouteChildren {
  AuthedAdminAuditRoute: typeof AuthedAdminAuditRoute
  AuthedAdminBoundariesRoute: typeof AuthedAdminBoundariesRoute
  AuthedAdminComponentsRoute: typeof AuthedAdminComponentsRoute
  AuthedAdminComputersRoute: typeof AuthedAdminComputersRoute
  AuthedAdminCredentialsRoute: typeof AuthedAdminCredentialsRoute
  AuthedAdminPlaygroundRoute: typeof AuthedAdminPlaygroundRoute
  AuthedAdminPluginsRoute: typeof AuthedAdminPluginsRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminAuditRoute: AuthedAdminAuditRoute,
  AuthedAdminBoundariesRoute: AuthedAdminBoundariesRoute,
  AuthedAdminComponentsRoute: AuthedAdminComponentsRoute,
  AuthedAdminComputersRoute: AuthedAdminComputersRoute,
  AuthedAdminCredentialsRoute: AuthedAdminCredentialsRoute,
  AuthedAdminPlaygroundRoute: AuthedAdminPlaygroundRoute,
  AuthedAdminPluginsRoute: AuthedAdminPluginsRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedSettingsRouteRouteChildren {
  AuthedSettingsAccountRoute: typeof AuthedSettingsAccountRoute
  AuthedSettingsConnectedAccountsRoute: typeof AuthedSettingsConnectedAccountsRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedSettingsRouteRouteChildren: AuthedSettingsRouteRouteChildren = {
  AuthedSettingsAccountRoute: AuthedSettingsAccountRoute,
  AuthedSettingsConnectedAccountsRoute: AuthedSettingsConnectedAccountsRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedSettingsRouteRouteWithChildren =
  AuthedSettingsRouteRoute._addFileChildren(AuthedSettingsRouteRouteChildren)

interface AuthedAppRouteChildren {
  AuthedAppRoutinesRoute: typeof AuthedAppRoutinesRoute
  AuthedAppSkillsRoute: typeof AuthedAppSkillsRoute
  AuthedAppIndexRoute: typeof AuthedAppIndexRoute
  AuthedAppApproveApprovalIdRoute: typeof AuthedAppApproveApprovalIdRoute
  AuthedAppChannelChannelIdRoute: typeof AuthedAppChannelChannelIdRoute
  AuthedAppChannelNewRoute: typeof AuthedAppChannelNewRoute
  AuthedAppAgentsIndexRoute: typeof AuthedAppAgentsIndexRoute
}

const AuthedAppRouteChildren: AuthedAppRouteChildren = {
  AuthedAppRoutinesRoute: AuthedAppRoutinesRoute,
  AuthedAppSkillsRoute: AuthedAppSkillsRoute,
  AuthedAppIndexRoute: AuthedAppIndexRoute,
  AuthedAppApproveApprovalIdRoute: AuthedAppApproveApprovalIdRoute,
  AuthedAppChannelChannelIdRoute: AuthedAppChannelChannelIdRoute,
  AuthedAppChannelNewRoute: AuthedAppChannelNewRoute,
  AuthedAppAgentsIndexRoute: AuthedAppAgentsIndexRoute,
}

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(
  AuthedAppRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  AuthedSettingsRouteRoute: typeof AuthedSettingsRouteRouteWithChildren
  AuthedAppRoute: typeof AuthedAppRouteWithChildren
  AuthedWelcomeRoute: typeof AuthedWelcomeRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  AuthedSettingsRouteRoute: AuthedSettingsRouteRouteWithChildren,
  AuthedAppRoute: AuthedAppRouteWithChildren,
  AuthedWelcomeRoute: AuthedWelcomeRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignRoute: SignRoute,
  UnreachableRoute: UnreachableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
