-- One outbox for "somebody has to be told", and the doors that carry it.
--
-- ADDITIVE, AND ONLY THAT. Nothing existing is touched: the approval registry stays in memory
-- (decision §7-1), the trail stays append-only, and a deployment that never reads this table
-- behaves exactly as it did. What it buys is a row per interruption, so "did that question ever
-- reach anybody" and "how long did an answer take at night" stop being unanswerable.
--
-- THE SNAPSHOT CHAIN SKIPS 0028, which is correct rather than an oversight. 0028 wrote three
-- functions and no table, and shipped without a snapshot of its own; this one is generated against
-- `0027_snapshot.json`, which is still an accurate picture of the tables at 0028. `drizzle-kit
-- check` reads that chain and passes.
--
-- Generated by `drizzle-kit generate`, then commented. See `server/src/db/schema/laf.ts` for why
-- `kind` is text, why `bot_id` has no foreign key and `user_id` does, and what `delivered_via` is
-- appended to rather than replaced by.

CREATE TABLE "laf_notifications" (
	"id" text PRIMARY KEY NOT NULL,
	"kind" text NOT NULL,
	"bot_id" text NOT NULL,
	"user_id" text NOT NULL,
	"approval_id" text,
	"channel_id" text,
	"subject" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"delivered_via" text[] DEFAULT '{}'::text[] NOT NULL,
	"delivered_at" timestamp with time zone,
	"seen_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "laf_notifications" ADD CONSTRAINT "laf_notifications_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "laf_notifications_user_created_at_idx" ON "laf_notifications" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "laf_notifications_approval_idx" ON "laf_notifications" USING btree ("approval_id");--> statement-breakpoint
CREATE INDEX "laf_notifications_created_at_idx" ON "laf_notifications" USING btree ("created_at");