-- One row per person per site: which Korean business sites they have signed into on a Bot's browser.
--
-- ADDITIVE, AND ONLY THAT. Nothing existing is touched, and a deployment that never reads this
-- table behaves exactly as it did. What it buys is a card that can say 연결됨 or 다시 로그인 필요
-- instead of asking somebody to remember which of fifteen sites they last logged into in March.
--
-- NOTHING SECRET IS IN HERE, by construction. The session is a cookie in the Chromium profile on
-- this person's own VM and never comes near Postgres — see `server/src/db/schema/laf.ts` for the
-- whole reasoning, and `server/tests/site-connections.test.ts` for the test that serialises a
-- connect and proves no typed value survives it.
--
-- Generated by `drizzle-kit generate`, then renamed and commented.

CREATE TABLE "laf_site_connections" (
	"user_id" text NOT NULL,
	"site_id" text NOT NULL,
	"bot_id" text NOT NULL,
	"connected_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"needs_login" boolean DEFAULT false NOT NULL,
	CONSTRAINT "laf_site_connections_user_id_site_id_pk" PRIMARY KEY("user_id","site_id")
);
--> statement-breakpoint
ALTER TABLE "laf_site_connections" ADD CONSTRAINT "laf_site_connections_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "laf_site_connections_user_idx" ON "laf_site_connections" USING btree ("user_id");