-- One row per person per partner vendor: which 카카오톡 채널 and which 팝빌 연동회원 are theirs.
--
-- ADDITIVE, AND ONLY THAT. Nothing existing is touched. What these two tables hold is not a
-- credential: LAF is the vendor's customer (a 솔라피 대행사 key, a 팝빌 LinkID) and each person is
-- REGISTERED under it, so what is per-person is the handle the vendor issued them. See
-- `server/src/db/schema/partners.ts` for why this is not `mcp_user_credentials`.
--
-- NO PASSWORD AND NO 인증번호 IS IN HERE. The 팝빌 연동회원 flow mints a password and forgets it, and
-- the 알림톡 인증번호 is spent inside one request. `server/tests/partner-connections.test.ts`
-- serialises a whole connect and proves neither survives it.
--
-- Generated by `drizzle-kit generate`, then commented.

CREATE TABLE "laf_alimtalk_templates" (
	"user_id" text NOT NULL,
	"code" text NOT NULL,
	"template_id" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"reason" text DEFAULT '' NOT NULL,
	"checked_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "laf_alimtalk_templates_user_id_code_pk" PRIMARY KEY("user_id","code")
);
--> statement-breakpoint
CREATE TABLE "laf_partner_connections" (
	"provider" text NOT NULL,
	"user_id" text NOT NULL,
	"account" text NOT NULL,
	"details" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"status" text DEFAULT 'linked' NOT NULL,
	"connected_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "laf_partner_connections_provider_user_id_pk" PRIMARY KEY("provider","user_id")
);
--> statement-breakpoint
ALTER TABLE "laf_alimtalk_templates" ADD CONSTRAINT "laf_alimtalk_templates_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "laf_partner_connections" ADD CONSTRAINT "laf_partner_connections_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "laf_alimtalk_templates_user_idx" ON "laf_alimtalk_templates" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "laf_partner_connections_user_idx" ON "laf_partner_connections" USING btree ("user_id");