-- Whether a connection still works, on the row that IS the connection.
--
-- Until this, `connectionsFor` could only say when somebody connected — so a grant the vendor
-- revoked months ago drew 연결됨 on the settings page for as long as nobody called a tool through
-- it, and the first anybody heard was a Bot failing mid-answer. The refresh already happens on
-- every call (one exchange per call, by design); it simply wrote nothing down.
--
-- ADDITIVE AND NULLABLE. A connection that predates this migration has neither column set, which
-- reads as `ok` — the honest answer for a row nothing has measured yet, and the same answer a
-- connection made a second ago deserves.
--
-- `last_failure_code` is one of OUR words (`revoked`, `refresh_failed`, `vendor_down`), never the
-- vendor's: its body is written for whoever registered the client, can name the client id, and is
-- in whatever language that vendor writes.
--
-- Generated by `drizzle-kit generate`, then commented.

ALTER TABLE "mcp_user_credentials" ADD COLUMN "last_ok_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "mcp_user_credentials" ADD COLUMN "last_failure_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "mcp_user_credentials" ADD COLUMN "last_failure_code" text;
