-- Routine suggestions, 2026-09-06: a curated catalogue of one-tap routines the /routines page
-- offers, consent-first. Hermes Agent's `cron/suggestions.py` is the shape being adopted — never
-- created on anybody's behalf, dismissed once means gone for good, at most five on screen.
--
-- ADDITIVE, AND ONLY THAT. `suggestion_key` on the routine is the dedup key: a suggestion is
-- offered until a routine carrying its key exists, and again once that routine is deleted, which
-- is why the key sits on the routine rather than in a ledger of acceptances. Every routine anybody
-- wrote by hand stays null. The dismissals table is the latch for 다음에, per person, and cascades
-- with the user row like `laf_site_connections` does; there is nothing in it but a catalogue word
-- and a clock.
--
-- Generated by `drizzle-kit generate --name routine_suggestions`, then commented.

CREATE TABLE "laf_routine_suggestion_dismissals" (
	"user_id" text NOT NULL,
	"suggestion_key" text NOT NULL,
	"dismissed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "laf_routine_suggestion_dismissals_user_id_suggestion_key_pk" PRIMARY KEY("user_id","suggestion_key")
);
--> statement-breakpoint
ALTER TABLE "laf_routines" ADD COLUMN "suggestion_key" text;--> statement-breakpoint
ALTER TABLE "laf_routine_suggestion_dismissals" ADD CONSTRAINT "laf_routine_suggestion_dismissals_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;