-- A routine's notepad, 2026-09-14: the few facts a routine carries from one run to the next —
-- above all where it left off.
--
-- Reply drafts for new reviews, answers for new inquiries, settlement mismatches: the jobs a shop
-- hands a routine first are all "since last time", and all that crossed from one run to the next
-- was the previous answer's prose, cut at 1,500 characters. That is not a cursor. Hermes Agent's
-- per-job notepad is the shape adopted (`cron/notepad.py`); the words, the bounds and the one tool
-- that writes it are ours (`shared/prompt/notepad.ko.ts`, `shared/tools/routine-note.ts`).
--
-- ADDITIVE, AND ONLY THAT. One row per routine, created by the first run that writes one, and
-- cascading with the routine. `entries` is a JSON array — the order a Bot wrote its entries in is
-- the order the next run and the person read them, which a jsonb object would not keep. `version`
-- is the fence a run's settlement writes over (`WHERE version =` the one the run read), so a person
-- clearing the notepad while a run is out wins over that run. `written_by_run` names the receipt of
-- the run whose settlement wrote it, as text: receipts are pruned to twenty and this row is not.
--
-- Generated by `drizzle-kit generate --name routine_notepad`, then commented.

CREATE TABLE "laf_routine_notepads" (
	"routine_id" text PRIMARY KEY NOT NULL,
	"entries" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"version" integer DEFAULT 0 NOT NULL,
	"written_by_run" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "laf_routine_notepads" ADD CONSTRAINT "laf_routine_notepads_routine_id_laf_routines_id_fk" FOREIGN KEY ("routine_id") REFERENCES "public"."laf_routines"("id") ON DELETE cascade ON UPDATE no action;
