-- Routines whose results pile up unread stop on their own, 2026-09-18.
--
-- A routine that runs every day while nobody opens the conversation it delivers into spends the
-- day's allowance and the shared model key on answers nobody reads, and the person does not notice.
-- The rule (`server/src/routines/unread.ts`) pauses such a routine; these columns are where it says
-- so, and where the person tells it not to.
--
--   paused_reason  why the routine is off when its person did not switch it off: 'unread'. Text,
--                  not an enum, so a second reason is a line of TypeScript rather than a migration.
--   paused_at      when that happened.
--   keep_running   the person's 계속 돌리기: never paused for going unread. Written by the person's
--                  own screen only — a Bot's `manage_routine` has no field that reaches it.
--   resumed_at     when a person last switched it back on. The rule counts from here too, so a
--                  routine somebody has just turned back on is not paused again for the pile that
--                  paused it, which is still unread.
--
-- ADDITIVE, AND ONLY THAT. Every existing routine reads as never paused, not exempt, never resumed,
-- which is exactly what each one is.
--
-- Generated by `drizzle-kit generate --name routine_unread_pause`, then commented.

ALTER TABLE "laf_routines" ADD COLUMN "paused_reason" text;--> statement-breakpoint
ALTER TABLE "laf_routines" ADD COLUMN "paused_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "laf_routines" ADD COLUMN "keep_running" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "laf_routines" ADD COLUMN "resumed_at" timestamp with time zone;
