-- The last picture of a browsing task, kept with the message it belongs to, 2026-09-24.
--
-- A browsing task leaves one card in the conversation, and the card shows what the Bot's browser
-- looked like when the task ended. The picture is a small JPEG the surface makes from the one
-- screenshot it takes at that moment, and it goes on the row of the task's last browser action's
-- result (`server/src/channels/frames.ts`).
--
-- A COLUMN, NOT A KEY IN `message`: every run hands the whole history back and a changed copy is
-- written over the row, which would erase a key the client never sends; and the newest rows'
-- `message` is read on every append, which a picture has no business riding along on.
--
-- ADDITIVE. Every existing message reads as having no picture, which is what each one has.
--
-- Generated by `drizzle-kit generate --name message_frame`, then commented.

ALTER TABLE "laf_thread_messages" ADD COLUMN "frame" text;
