-- What rooms and several Bots a person left behind, dropped. 2026-09-24.
--
-- A person has one Bot since that morning, and rooms and one Bot asking another were deleted from
-- the code the same day (docs/laf/deployment-model.md, "봇은 하나다"). That change dropped nothing
-- and listed what it left. The owner, the same afternoon: "남아있는 테이블은 삭제처리해." This is
-- that list, gone.
--
-- ROOMS GO, ROWS AND ALL. A room is a channel with more than one Bot in it, and nothing can open
-- one any more, so what it held can be read by nobody: its thread messages, the runs recorded
-- against its threads, the notifications that pointed into it, and the channel itself — whose
-- delete cascades to its memberships, its Bots, its per-person threads and the answer ratings in
-- it. The test is the count of `channel_agents` and nothing else, so a conversation with ONE Bot is
-- never touched; `server/tests/drop-multi-bot-leftovers.integration.test.ts` seeds both and proves
-- it. A room whose other members were taken out before 2026-09-24 has one Bot and is a 1:1
-- conversation by that same test, and stays.
--
-- `laf_run_origin` LOSES `room` AND `handoff`. The runs carrying them are deleted first — the
-- retyping below would refuse them — rather than rewritten as `chat`, which they were not. A run row
-- is the operational skeleton of what the machine did and ages out at a year anyway; the history of
-- record is the audit trail, and its `room.member_turn` and `coworker.asked` rows are NOT touched
-- here or anywhere: an append-only trail is the one thing a cleanup must not edit.
--
-- `lafRoomReceipts` was a key a room wrote into a person's message. It goes with the rooms, and is
-- taken off any row still carrying it — a room reduced to one Bot kept its messages.
--
-- THE COLUMNS. `agent_profiles.title` and `preset_id`: a profile is a name and a face, and nothing
-- has written either since the presets went. `channels.room_turn_epoch`: the rooms' turn counter.
-- `agent_preferences.pinned_at`: pinning ordered a roster of several Bots, and neither the app nor
-- the server has read it since. `agent_preferences.hidden_at` stays — the switcher an account with
-- several Bots still sees lists hidden ones last.
--
-- On a database that never had a room every DELETE matches nothing and the rest is DDL.
--
-- Generated by `drizzle-kit generate --name drop_multi_bot_leftovers`, then commented, with the
-- data statements put in front of the DDL they have to precede (as 0038 does).

DELETE FROM "laf_thread_messages"
WHERE "thread_id" IN (
  SELECT "thread_id" FROM "channel_threads"
  WHERE "channel_id" IN (
    SELECT "channel_id" FROM "channel_agents" GROUP BY "channel_id" HAVING count(*) > 1
  )
);--> statement-breakpoint
DELETE FROM "laf_thread_runs"
WHERE "origin" IN ('room', 'handoff')
   OR "thread_id" IN (
     SELECT "thread_id" FROM "channel_threads"
     WHERE "channel_id" IN (
       SELECT "channel_id" FROM "channel_agents" GROUP BY "channel_id" HAVING count(*) > 1
     )
   );--> statement-breakpoint
DELETE FROM "laf_notifications"
WHERE "channel_id" IN (
  SELECT "channel_id" FROM "channel_agents" GROUP BY "channel_id" HAVING count(*) > 1
);--> statement-breakpoint
DELETE FROM "channels"
WHERE "id" IN (
  SELECT "channel_id" FROM "channel_agents" GROUP BY "channel_id" HAVING count(*) > 1
);--> statement-breakpoint
UPDATE "laf_thread_messages"
SET "message" = "message" - 'lafRoomReceipts'
WHERE jsonb_typeof("message") = 'object' AND "message" ? 'lafRoomReceipts';--> statement-breakpoint
ALTER TABLE "laf_thread_runs" ALTER COLUMN "origin" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "laf_thread_runs" ALTER COLUMN "origin" SET DEFAULT 'chat'::text;--> statement-breakpoint
DROP TYPE "public"."laf_run_origin";--> statement-breakpoint
CREATE TYPE "public"."laf_run_origin" AS ENUM('chat', 'routine', 'wake');--> statement-breakpoint
ALTER TABLE "laf_thread_runs" ALTER COLUMN "origin" SET DEFAULT 'chat'::"public"."laf_run_origin";--> statement-breakpoint
ALTER TABLE "laf_thread_runs" ALTER COLUMN "origin" SET DATA TYPE "public"."laf_run_origin" USING "origin"::"public"."laf_run_origin";--> statement-breakpoint
ALTER TABLE "channels" DROP COLUMN "room_turn_epoch";--> statement-breakpoint
ALTER TABLE "agent_preferences" DROP COLUMN "pinned_at";--> statement-breakpoint
ALTER TABLE "agent_profiles" DROP COLUMN "title";--> statement-breakpoint
ALTER TABLE "agent_profiles" DROP COLUMN "preset_id";
