-- A routine's one line for the person, 2026-09-24 (UI/UX audit 0.5.3, item 8).
--
-- A routine a Bot made in conversation showed its instruction on the Routines screen, and that
-- instruction is written for the Bot's future self: "매주 월요일 아침이다. 사용자에게 지난주 매출
-- 요약을 요청하는 인사와 함께 …". The Bot now writes a line for the person beside it through
-- `manage_routine`, and the screen shows that line; the instruction is still there, folded.
--
--   summary  what the routine does, said to the person. Never sent to the Bot. Null on every
--            routine made before this, on routines written by hand, and after an edit that changes
--            the instruction or the schedule without a new summary — the screen then shows the
--            instruction itself rather than a line describing a routine that is no longer this one.
--
-- ADDITIVE, AND ONLY THAT. Every existing routine reads as having no summary, which is true.
--
-- Generated by `drizzle-kit generate --name routine_summary`, then commented.

ALTER TABLE "laf_routines" ADD COLUMN "summary" text;
