-- The person's clock and place, 2026-09-24 ("날짜, 시간, 위치는 사용자의 정보를 사용하도록").
--
-- Asked for today's weather, a Bot searched 네이버 and reported 제주시 as "사장님 위치": the site had
-- guessed from the address of the Bot's browser, which runs on a cloud VM. The VM's zone and place
-- are not the person's, so the person's own are kept here and told to every run and to the browser.
--
--   time_zone, locale     what the person's device reported the last time the app was opened; the
--                         clock a routine reads, since a routine runs with no device present.
--   place                 a city or district, set on 내 가게 or said in a conversation.
--   place_lat, place_lon  from the device, with the person's permission, rounded to two decimals.
--
-- ADDITIVE, AND ONLY THAT. Every existing account reads as having told us nothing, which is true;
-- nothing is backfilled, because a place nobody gave would be told to every run as theirs.
--
-- Generated by `drizzle-kit generate --name person_whereabouts`, then commented.

ALTER TABLE "users" ADD COLUMN "time_zone" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "locale" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "place" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "place_lat" double precision;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "place_lon" double precision;
