import { mkdir, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, resolve } from "node:path";
import {
  createApplicationConfiguration,
  loadTenantPackage,
} from "../server/src/tenant-package";

const projectRoot = resolve(import.meta.dir, "..");
const configuredTenantPackageDirectory = process.env.TENANT_PACKAGE_DIR;
const tenantPackageDirectory = configuredTenantPackageDirectory
  ? isAbsolute(configuredTenantPackageDirectory)
    ? configuredTenantPackageDirectory
    : resolve(projectRoot, "server", configuredTenantPackageDirectory)
  : resolve(projectRoot, "tenant/laf");
const tenantPackage = await loadTenantPackage(tenantPackageDirectory);
/*
 * Which sign-in providers the surface FALLS BACK to, compiled in.
 *
 * The buttons actually drawn come from the running server (`GET /api/auth/providers`,
 * `app/src/lib/auth/providers.ts`); this list is where the screen lands when the server cannot
 * answer. It was the whole answer until 2026-09-06, and the fleet measured what that meant: an
 * image built for `google` on a VM whose `.env` said `laf`.
 *
 * AUTH_PROVIDERS is the explicit form, and it exists for the container build: passing the real
 * credentials as build args writes them into the image's history, and a build only ever needed to
 * know WHETHER a provider is configured. Unset — a local `bun run dev` — it falls back to reading
 * the credentials, so nothing about developing here changed.
 */
const authReady =
  process.env.BETTER_AUTH_SECRET?.trim() && process.env.BETTER_AUTH_URL?.trim();
const credentialled = (["google", "kakao", "naver"] as const).filter(
  (provider) =>
    process.env[`${provider.toUpperCase()}_OAUTH_CLIENT_ID`]?.trim() &&
    process.env[`${provider.toUpperCase()}_OAUTH_CLIENT_SECRET`]?.trim(),
);
const providers =
  process.env.AUTH_PROVIDERS !== undefined
    ? process.env.AUTH_PROVIDERS.split(",")
        .map((provider) => provider.trim())
        .filter(Boolean)
    : authReady
      ? credentialled
      : [];
const applicationConfiguration = createApplicationConfiguration(
  tenantPackage,
  providers,
);
const outputPath = resolve(
  projectRoot,
  "app/src/lib/generated/application-config.ts",
);

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  [
    "// This file is generated by scripts/generate-app-config.ts. Do not edit it.",
    "export type AppConfig = { brand: { tenantId: string; productName: string }; auth: { providers: readonly string[] } };",
    `export const appConfig: AppConfig = ${JSON.stringify(applicationConfiguration, null, 2)};`,
    "",
  ].join("\n"),
);
